version: "3"
services:
    app:
        container_name: "app"
        # restart: always
        build: ./
        ports:
            - "9222:9222"
            - "3000:3000"
        # volumes:
        # 	- .:/app
        links:
            - "mongo"
    mongo:
        container_name: "mongo"
        image: "mongo:4"
        ports:
            - "27017:27017"
